@LoginAuthenticationSystem_HostAddress = http://localhost:5159

### Register
POST {{LoginAuthenticationSystem_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "fullName": "Demo User",
  "email": "demo@example.com",
  "password": "Password123!"
}

### Login
# @name login
POST {{LoginAuthenticationSystem_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "demo@example.com",
  "password": "Password123!"
}

### Current User
GET {{LoginAuthenticationSystem_HostAddress}}/api/auth/me
Authorization: Bearer {{login.response.body.$.token}}
Accept: application/json

###
